In [1]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [30]:
# Create tensors with tf.constant()
scalarVar = tf.constant(7)
scalarVar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [33]:
# check the number of dimensions of a tensor (ndim stans  for number of dimensions)
scalarVar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

In [ ]:
# Check the dimension of our vector
vector.ndim

In [ ]:
#create a matrix ( has more than 1 dimention)
matrix =  tf.constant([[10 , 4],
                       [7 , 10]])
matrix

In [ ]:
matrix.ndim

In [ ]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix                        

In [ ]:
another_matrix.ndim # another_matrix dimention

In [ ]:
#lets create a tensor
tensor =  tf.constant([[[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                        [10,11,12]]])
tensor

## **Creeating tensors with tf.variable**

In [ ]:
#create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

In [ ]:
# let's try to change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# let's try to change one of the elements in our unchangeable/constant tensor
unchangeable_tensor[0].assign(5)
unchangeable_tensor
#unchangeable tensor cann't be edited

**NOTE**: Rarely in practice you will need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, If in doubt , use tf.constant and change it later if needed.

***Creating random number ***

Random tensors ae tensors of some abitrary size which contain random numbers


In [ ]:
# Create two random (but the same) tensors
random_1 =  tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

#are they equal?
random_1, random_2, random_1 == random_2

**Shuffle the order of elements in tensor**

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning
not_shuffle =  tf.constant([[8, 9],
                            [9,11],
                            [5, 6]])
not_shuffle

In [ ]:
#shuffle our non-shuffle tensor
tf.random.shuffle(not_shuffle)  

In [ ]:
# SEED
 #tf.random.set_seed(42) - global
tf.random.shuffle(not_shuffle, seed = 42) # operation level random seed


***SEED : global and operational***

https://www.tensorflow.org/api_docs/python/tf/random/set_seed


It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random as well as the operation level random Seed:

**RULE :**If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

**Other ways to make tensors**

In [ ]:
tf.ones([10, 7])

In [ ]:
tf.zeros(shape = (3, 4)) # create a tensor of al zeros

### Turn numpy into tensors

the main difference between Numpy arrays and tensorflow tensors can be run on a GPU (much faster for numarical computing)

In [ ]:
# you can also turn Numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpy_A

In [ ]:
A = tf.constant(numpy_A)
A

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

Getting information from **tensors**

### when dealing with tensors you probably want to be aware of following attributes:


*   Shape
*   Rank
*   Axis or dimension
*   Size


In [41]:
 # Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros( shape =[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensiion (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())


**Indexing tensor**

tensor can be indexed just like python lists

In [39]:
some_list = [1, 2, 3, 4]
some_list

[1, 2, 3, 4]

In [42]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2 , :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1 , :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [35]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim,rank_2_tensor

(TensorShape([2, 2]),
 2,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>)

In [44]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [45]:
#GEt the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [46]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis] #... means [:, : , tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [47]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means dim er sheke 1 dim add hobe


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [48]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) #expand at 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [49]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

**### Manipulating tensors (tensor Operation)**

** Basic operation **

+ , - , * , / 


In [8]:
 # You can add values to a tensor using the addition operation
tensor =  tf.constant([[10, 7],
                        [3, 4]])
tensor +10 # also works as subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [9]:
# original tensor unchanged
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [10]:
# Multiplication/divition also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [11]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [12]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

**Matrix Multiplication**

In [13]:
# matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [14]:
tensor, tensor * tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>)

In [15]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [16]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [17]:
X = tf.constant([[1, 2, 5],
                 [7, 2, 1],
                 [3, 3, 3]])
Y = tf.constant([[3, 5],
                [6, 7],
                [1, 8]]) 
alt = tf.ones([3, 2])
X @ Y, alt

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]])>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

In [18]:
# Try to matrix muliply tensor of same shape

In [19]:
# Let's change the shape of Y
tf.reshape(X, shape=(1, 9))

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 2, 5, 7, 2, 1, 3, 3, 3]])>

In [20]:
# reshape and multiply
X, Y, X @ tf.reshape(Y, shape=(3, 2))

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[20, 59],
        [34, 57],
        [30, 60]])>)

In [21]:
# Transpose
tf.transpose(alt), Y,  tf.reshape(Y, shape=(3, 2))

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

**The DOT PRODUCT**

Matrix multiplication is also referred to as the dot product

You can perform matrix multiplication using : 


*   tf.matmul()
*   tf.rensordot()


In [22]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1), X.shape, Y.shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[48, 78],
        [21, 48],
        [24, 56]])>,
 TensorShape([3, 3]),
 TensorShape([3, 2]))

In [23]:
X @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [24]:
# Difference between reshape and transpose
X.shape, Y.shape , alt.shape

(TensorShape([3, 3]), TensorShape([3, 2]), TensorShape([3, 2]))

In [25]:
#Var1 = tf.ones([3,2])
Var2 = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
Var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [26]:
#tf.reshape(B, shape= (3,2))